"use client";

import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";

export default function CadastroPage() {
  const [erro,setErro]=useState<string|null>(null); const [loading,setLoading]=useState(false); const router=useRouter();
  async function cadastrar(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setErro(null);const fd=new FormData(e.currentTarget);const nome=String(fd.get("nome"));const escritorio=String(fd.get("escritorio")||"");const oab=String(fd.get("oab")||"");const email=String(fd.get("email"));const password=String(fd.get("senha"));const supabase=createClient();const {data,error}=await supabase.auth.signUp({email,password,options:{data:{nome,escritorio,oab}}});if(error){setErro(error.message);setLoading(false);return;}if(data.user&&data.session){await supabase.from("perfis").upsert({id:data.user.id,nome,escritorio:escritorio||null,oab:oab||null});router.push("/hoje");router.refresh();return;}setLoading(false);setErro("Cadastro criado. Confira seu e-mail para confirmar a conta e depois faça login.");}
  return <main className="min-h-screen bg-[#08111f] px-5 py-10 flex items-center justify-center"><section className="w-full max-w-[500px] card p-7 sm:p-9"><div className="text-center mb-7"><img src="/icon.svg" alt="ADV Simples" className="w-20 h-20 mx-auto mb-4"/><p className="text-secondary text-[10px] uppercase tracking-[.24em] font-semibold">Primeiro acesso</p><h1 className="font-heading text-3xl font-bold text-white mt-2">Crie seu escritório</h1><p className="text-sm text-on-surface-variant mt-2">Seu ambiente será privado e separado dos demais advogados.</p></div>{erro&&<div className="mb-4 rounded-xl border border-secondary/20 bg-secondary/5 p-3 text-sm text-on-surface">{erro}</div>}<form onSubmit={cadastrar} className="space-y-3"><input name="nome" required placeholder="Seu nome"/><input name="escritorio" placeholder="Nome do escritório (opcional)"/><input name="oab" placeholder="OAB (opcional)"/><input name="email" type="email" required placeholder="E-mail"/><input name="senha" type="password" required minLength={8} placeholder="Senha (mínimo 8 caracteres)"/><button disabled={loading} className="w-full bg-secondary text-on-secondary font-heading font-bold py-3">{loading?"Criando ambiente...":"Criar meu ADV Simples"}</button></form><a href="/login" className="block text-center text-sm text-on-surface-variant mt-5 hover:text-secondary">Já tenho conta · Entrar</a></section></main>;
}
