import { createClient } from "@/lib/supabase/server";
import { reportServerError } from "@/lib/report-server-error";
import { revalidatePath } from "next/cache";
import Nav from "../nav";
import PremiumSelect from "../premium-select";

function moeda(v:number|string){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});}
function whats(tel:string|null,msg:string){if(!tel)return null;let d=tel.replace(/\D/g,"");if(d.length===10||d.length===11)d=`55${d}`;return `https://wa.me/${d}?text=${encodeURIComponent(msg)}`;}

async function criarCobranca(formData:FormData){"use server";const supabase=await createClient();const {error}=await supabase.from("cobrancas").insert({cliente_id:formData.get("cliente_id") as string,caso_id:(formData.get("caso_id") as string)||null,descricao:formData.get("descricao") as string,valor:Number(String(formData.get("valor")).replace(",",".")),vencimento:formData.get("vencimento") as string,observacao:(formData.get("observacao") as string)||null});if(error){await reportServerError(supabase,"criar_cobranca","/financeiro",error);throw new Error("Não foi possível cadastrar a cobrança.");}revalidatePath("/financeiro");revalidatePath("/hoje");}
async function marcarPago(formData:FormData){"use server";const supabase=await createClient();const {error}=await supabase.from("cobrancas").update({pago:true,pago_em:new Date().toISOString().slice(0,10),forma_pagamento:(formData.get("forma") as string)||"Recebido"}).eq("id",formData.get("id"));if(error){await reportServerError(supabase,"marcar_cobranca_paga","/financeiro",error);throw new Error("Não foi possível marcar a cobrança como paga.");}revalidatePath("/financeiro");revalidatePath("/hoje");}

export default async function FinanceiroPage(){
 const supabase=await createClient();
 const [clientesRes,casosRes,cobrancasRes]=await Promise.all([
  supabase.from("clientes").select("id,nome,telefone").order("nome"),
  supabase.from("casos").select("id,titulo,cliente_id").order("titulo"),
  supabase.from("cobrancas").select("id,descricao,valor,vencimento,pago,pago_em,forma_pagamento,clientes(nome,telefone),casos(titulo)").order("vencimento",{ascending:true})
 ]);
 if(clientesRes.error){await reportServerError(supabase,"listar_clientes_financeiro","/financeiro",clientesRes.error);throw new Error("Não foi possível carregar o financeiro.");}
 if(casosRes.error){await reportServerError(supabase,"listar_casos_financeiro","/financeiro",casosRes.error);throw new Error("Não foi possível carregar o financeiro.");}
 if(cobrancasRes.error){await reportServerError(supabase,"listar_cobrancas","/financeiro",cobrancasRes.error);throw new Error("Não foi possível carregar o financeiro.");}
 const clientes=clientesRes.data,casos=casosRes.data,cobrancas=cobrancasRes.data;
 const hoje=new Date();hoje.setHours(0,0,0,0);const inicioMes=new Date(hoje.getFullYear(),hoje.getMonth(),1);const fim30=new Date(hoje);fim30.setDate(fim30.getDate()+30);
 const lista=cobrancas??[];const recebidoMes=lista.filter((c:any)=>c.pago&&c.pago_em&&new Date(c.pago_em+"T00:00:00")>=inicioMes).reduce((s:number,c:any)=>s+Number(c.valor),0);
 const aReceber30=lista.filter((c:any)=>!c.pago&&new Date(c.vencimento+"T00:00:00")>=hoje&&new Date(c.vencimento+"T00:00:00")<=fim30).reduce((s:number,c:any)=>s+Number(c.valor),0);
 const atrasado=lista.filter((c:any)=>!c.pago&&new Date(c.vencimento+"T00:00:00")<hoje).reduce((s:number,c:any)=>s+Number(c.valor),0);
 const pendentes=lista.filter((c:any)=>!c.pago);
 return <div className="min-h-screen bg-transparent flex flex-col pb-28"><Nav active="financeiro"/><main className="flex-1 w-full max-w-2xl mx-auto px-margin-mobile py-xl flex flex-col gap-xl">
  <header><p className="text-secondary text-[11px] uppercase tracking-[.24em] font-semibold mb-2">Controle simples</p><h1 className="font-heading text-4xl font-bold text-on-surface">Financeiro</h1><p className="text-on-surface-variant text-sm mt-2">Saiba o que recebeu, o que vai receber e quem precisa ser cobrado.</p></header>
  <section className="grid grid-cols-3 gap-3"><div className="card p-4 text-center"><p className="text-xl font-heading font-bold text-on-surface">{moeda(recebidoMes)}</p><p className="text-[9px] uppercase tracking-wider text-on-surface-variant mt-1">Recebido no mês</p></div><div className="card p-4 text-center"><p className="text-xl font-heading font-bold text-secondary">{moeda(aReceber30)}</p><p className="text-[9px] uppercase tracking-wider text-on-surface-variant mt-1">Próx. 30 dias</p></div><div className="card p-4 text-center"><p className="text-xl font-heading font-bold text-error">{moeda(atrasado)}</p><p className="text-[9px] uppercase tracking-wider text-on-surface-variant mt-1">Em atraso</p></div></section>
  <section className="card p-5 sm:p-6"><div className="flex items-center gap-3 mb-5"><div className="w-10 h-10 rounded-xl flex items-center justify-center bg-secondary/10 border border-secondary/20"><span className="material-symbols-outlined text-secondary">payments</span></div><div><h2 className="font-heading text-lg font-semibold text-on-surface">Nova cobrança</h2><p className="text-xs text-on-surface-variant">Honorário, parcela ou qualquer valor a receber.</p></div></div>
   {(clientes??[]).length===0?<p className="text-sm text-on-surface-variant">Cadastre um cliente primeiro.</p>:<form action={criarCobranca} className="space-y-3"><PremiumSelect name="cliente_id" placeholder="Cliente" options={(clientes??[]).map((c:any)=>({value:c.id,label:c.nome}))}/><PremiumSelect name="caso_id" placeholder="Caso (opcional)" options={[{value:"",label:"Sem caso vinculado"},...(casos??[]).map((c:any)=>({value:c.id,label:c.titulo}))]}/><input name="descricao" required placeholder="Ex.: Honorários — parcela 2/5" className="px-4 py-3"/><div className="grid grid-cols-2 gap-3"><input name="valor" inputMode="decimal" required placeholder="Valor" className="px-4 py-3"/><input name="vencimento" type="date" required className="px-4 py-3"/></div><input name="observacao" placeholder="Observação (opcional)" className="px-4 py-3"/><button className="w-full bg-secondary text-on-secondary font-heading font-bold py-3">Cadastrar cobrança</button></form>}
  </section>
  <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-heading font-bold text-on-surface">A receber</h2><span className="text-xs text-on-surface-variant">{pendentes.length} pendente(s)</span></div>{pendentes.length===0&&<div className="card p-7 text-center text-on-surface-variant">Nenhuma cobrança pendente.</div>}{pendentes.map((c:any)=>{const venc=new Date(c.vencimento+"T00:00:00");const vencido=venc<hoje;const tel=c.clientes?.telefone??null;const msg=`Olá, ${c.clientes?.nome??""}. Passando para lembrar sobre ${c.descricao}, no valor de ${moeda(c.valor)}, com vencimento em ${venc.toLocaleDateString("pt-BR")}.`;const url=whats(tel,msg);return <article key={c.id} className={`card p-5 ${vencido?"border-l-[3px] urgency-overdue":""}`}><div className="flex justify-between gap-4"><div className="min-w-0"><span className={`text-[9px] uppercase tracking-wider px-2.5 py-1 rounded-full border ${vencido?"text-error border-error/20 bg-error/10":"text-secondary border-secondary/20 bg-secondary/10"}`}>{vencido?"Atrasado":"A receber"}</span><h3 className="font-heading text-lg font-bold text-on-surface mt-2">{c.descricao}</h3><p className="text-sm text-on-surface-variant mt-1">{c.clientes?.nome??"Cliente"}{c.casos?.titulo?` · ${c.casos.titulo}`:""}</p><p className="text-xs text-on-surface-variant mt-2">Vence em {venc.toLocaleDateString("pt-BR")}</p></div><div className="text-right shrink-0"><p className="font-heading text-xl font-bold text-secondary">{moeda(c.valor)}</p></div></div><div className="grid grid-cols-2 gap-2 mt-4">{url?<a href={url} target="_blank" rel="noreferrer" className="min-h-[46px] rounded-xl border border-emerald-500/25 bg-emerald-500/10 text-emerald-500 font-semibold text-sm flex items-center justify-center gap-2"><span className="material-symbols-outlined text-[19px]">chat</span>Cobrar no WhatsApp</a>:<div className="min-h-[46px] rounded-xl border border-outline-variant/30 flex items-center justify-center text-xs text-on-surface-variant">Cliente sem telefone</div>}<form action={marcarPago}><input type="hidden" name="id" value={c.id}/><input type="hidden" name="forma" value="Recebido"/><button className="w-full h-[46px] !min-h-0 bg-secondary text-on-secondary font-bold">Marcar como pago</button></form></div></article>})}</section>
 </main></div>;
}
